name: example
dependencies:
  hive: any
dev_dependencies:
  build_runner: any
  hive_generator:
    path: ..
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependency_overrides:
  hive:
    git:
      url: https://github.com/petroczizoltan/hive
      ref: add_custom_constructor_support_to_hive_type
      path: hive
  hive_generator:
    git:
      url: https://github.com/petroczizoltan/hive
      ref: add_custom_constructor_support_to_hive_type
      path: hive_generator
