name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 1.1.3
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  hive:
    git:
      url: https://github.com/petroczizoltan/hive
      ref: add_custom_constructor_support_to_hive_type
      path: hive
  analyzer: ">=5.2.0 <6.0.0"
  source_helper: ^1.1.0

dev_dependencies:
  test: ^1.17.11
  build_test: any
  build_runner: any
  pedantic: ^1.11.1
